import os

scripts = os.listdir("project/resources/scripts")
print(scripts)

includesFile = open("project/resources/scripts/com.demensdeum.flamesteelengine.application.includes.js", "w")
includesFile.write("//Generated by compileIncludes.py script\n")
includesFile.write("function IncludeDependencies() {\n")
for script in scripts:
    if script == "com.demensdeum.flamesteelengine.application.includes.js":
        continue
    if script == "com.demensdeum.flamesteelengine.application.main.js":
        continue
    includesFile.write(f"\tinclude(\"{script}\");\n")
includesFile.write("};\n")
includesFile.close()
